language: php

php:
  - 7.0

sudo: true

addons:
  apt:
    packages:
      - nginx
  hosts:
    - travis.dev

before_script:
  - sudo sh $TRAVIS_BUILD_DIR/scripts/travis_nginx.sh
  - cd $TRAVIS_BUILD_DIR/web
  - php -S 127.0.0.1:8080 &
  - sleep 3

script: sudo sh $TRAVIS_BUILD_DIR/scripts/curl_test.sh
